
############################### OUTPUT ###############################

## ROOT output
/gate/output/root/enable
/gate/output/root/setFileName output/ROOT_MEGP
/gate/output/root/setRootHitFlag 0
/gate/output/root/setRootSinglesFlag 1
/gate/output/root/setRootNtupleFlag 0
#/gate/output/root/setRootSinglesAdderFlag 0
#/gate/output/root/setRootSinglesBlurringFlag 0
#/gate/output/root/setRootSinglesSpblurringFlag 0
#/gate/output/root/setRootSinglesThresholderFlag 1
#/gate/output/root/setRootSinglesUpholderFlag 1
#/gate/output/root/setSaveRndmFlag 0

/gate/output/projection/enable
/gate/output/projection/setInputDataName Photopeak
/gate/output/projection/setFileName PROJECTION_MEGP
/gate/output/projection/projectionPlane YZ
/gate/output/projection/pixelSizeX 0.234 cm
/gate/output/projection/pixelSizeY 0.234 cm
/gate/output/projection/pixelNumberX 230
/gate/output/projection/pixelNumberY 170


